-- Alertas con destinatarios puntuales (varias personas) y matriz de roles nueva (src/lib/alertas/destinatarios.ts).
ALTER TABLE "Alerta" ADD COLUMN "usuariosDestino" TEXT[] DEFAULT ARRAY[]::TEXT[];
UPDATE "Alerta" SET "usuariosDestino" = ARRAY["usuarioId"] WHERE "usuarioId" IS NOT NULL;
UPDATE "Alerta" SET "rolesDestino" = CASE "regla"
  WHEN 'PENDIENTE_HOY' THEN ARRAY['DIRECCION', 'CHOFER']::"Rol"[]
  WHEN 'URGENTE_SIN_TOMAR' THEN ARRAY['DIRECCION', 'CHOFER']::"Rol"[]
  WHEN 'DUPLICADO' THEN ARRAY['DIRECCION']::"Rol"[]
  WHEN 'VIAJE_LARGO' THEN ARRAY['DIRECCION']::"Rol"[]
  WHEN 'PARADO_EN_VIAJE' THEN ARRAY['DIRECCION', 'ADMINISTRACION']::"Rol"[]
  WHEN 'FUERA_HORARIO' THEN ARRAY['DIRECCION', 'ADMINISTRACION']::"Rol"[]
  WHEN 'DOCUMENTO' THEN ARRAY['DIRECCION', 'ADMINISTRACION']::"Rol"[]
  WHEN 'SERVICE' THEN ARRAY['DIRECCION', 'ADMINISTRACION']::"Rol"[]
  WHEN 'CONSUMO' THEN ARRAY['DIRECCION', 'ADMINISTRACION']::"Rol"[]
  WHEN 'LICENCIA' THEN ARRAY['DIRECCION', 'ADMINISTRACION']::"Rol"[]
  WHEN 'DEVOLUCION_VENCIDA' THEN ARRAY['DIRECCION', 'DEPOSITO']::"Rol"[]
  WHEN 'MAQUINA_OBRA_PARADA' THEN ARRAY['DIRECCION', 'DEPOSITO']::"Rol"[]
  WHEN 'MANT_MAQUINA' THEN ARRAY['DIRECCION', 'DEPOSITO']::"Rol"[]
  ELSE ARRAY['DIRECCION']::"Rol"[] END;
CREATE INDEX "Alerta_usuariosDestino_idx" ON "Alerta" USING GIN ("usuariosDestino");
CREATE INDEX "Alerta_rolesDestino_idx" ON "Alerta" USING GIN ("rolesDestino");
