/**
 * Inventario real de herramientas de Signa (planilla "Inventario SIGNA", hoja "Herramientas").
 * Solo el nombre y la cantidad total: las filas con el mismo nombre se suman y TODO queda en el
 * depósito, diga lo que diga la planilla sobre la locación. 117 herramientas, 1108 unidades.
 * esMaquina: las que se trasladan en camión (hormigoneras, vibradoras, montacargas, generador…).
 * Generado desde la planilla; para volver a cargarlo, editar esta lista.
 */
export type HerramientaInventario = { nombre: string; categoria: string; cantidad: number; esMaquina?: boolean };

export const INVENTARIO_HERRAMIENTAS: HerramientaInventario[] = [
  { nombre: "Alargue C/ reflectores", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Amoladora SKILL", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Balde Albañil", categoria: "Herramientas manuales y pesadas", cantidad: 5 },
  { nombre: "Bomba Sumergible de Desagote", categoria: "Herramientas manuales y pesadas", cantidad: 3 },
  { nombre: "Cizalla C/ Palanca", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Corta Alambre GRANDE", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Escalera metalica 7 Escalones", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Escobillones Barrenderos", categoria: "Herramientas manuales y pesadas", cantidad: 4 },
  { nombre: "Fratacho Madera", categoria: "Herramientas manuales y pesadas", cantidad: 3 },
  { nombre: "Hidrolavadora INECO", categoria: "Herramientas manuales y pesadas", cantidad: 1, esMaquina: true },
  { nombre: "Manguera P/ Bomba celeste", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Martillo Demoledor STAYER Mod MDM 15 KB", categoria: "Herramientas manuales y pesadas", cantidad: 1, esMaquina: true },
  { nombre: "Mochila Fumigadora 20 L", categoria: "Herramientas manuales y pesadas", cantidad: 3 },
  { nombre: "Pala Ancha", categoria: "Herramientas manuales y pesadas", cantidad: 6 },
  { nombre: "Pala Punta", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Pico", categoria: "Herramientas manuales y pesadas", cantidad: 3 },
  { nombre: "Sierra Circular LUQTOFF Mod SCL2200", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Sierra Ingletadora EINHELL Mod TC-MS216", categoria: "Herramientas manuales y pesadas", cantidad: 1, esMaquina: true },
  { nombre: "Sierra Sable TOTAL Mod TS100", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Sopladora de Aire HAMILTON Mod HSA001", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Amarre de Fuerza", categoria: "Seguridad personal", cantidad: 1 },
  { nombre: "Arnes de Seguridad P/ Altura", categoria: "Seguridad personal", cantidad: 7 },
  { nombre: "Botas", categoria: "Seguridad personal", cantidad: 7 },
  { nombre: "Camisas de Trabajo", categoria: "Seguridad personal", cantidad: 3 },
  { nombre: "Casco Amarillo Seguridad", categoria: "Seguridad personal", cantidad: 17 },
  { nombre: "Faja Lumbar", categoria: "Seguridad personal", cantidad: 1 },
  { nombre: "Maletin Gris Ind. Saladillo", categoria: "Seguridad personal", cantidad: 1 },
  { nombre: "Vibradoras Hormigon", categoria: "Herramientas manuales y pesadas", cantidad: 2, esMaquina: true },
  { nombre: "Tolba descarga escombro", categoria: "Herramientas manuales y pesadas", cantidad: 16 },
  { nombre: "Amoladora BOSCH 5\" GWS 855", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Amoladora BOSCH 9\" GWS 28-230", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Amoladora MAKITA 9\" GA7820", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Carretillas", categoria: "Herramientas manuales y pesadas", cantidad: 5 },
  { nombre: "Cepilladora KOMMBERG KB-CE650", categoria: "Herramientas manuales y pesadas", cantidad: 1, esMaquina: true },
  { nombre: "Corta Ceramica", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Escalera Madera 5 escalones", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Garrafa C/ Soplete (P/menbrana)", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Hormigonera de Tambor", categoria: "Herramientas manuales y pesadas", cantidad: 3, esMaquina: true },
  { nombre: "Lijadora BLACK-DECKER QS1000-AR", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Martillo Demoledor GSH 11 BOSCH", categoria: "Herramientas manuales y pesadas", cantidad: 1, esMaquina: true },
  { nombre: "Martillo Perforador GBH-2-26 BOSCH", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Mascara P/ Soldar", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Mescladora MANUAL BLACK-DECKER", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Moto Sierra a explision HUSQVARMA", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Nivel Laser BREMEN 7287", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Soldadora LUQTOFF Iron-100", categoria: "Herramientas manuales y pesadas", cantidad: 1, esMaquina: true },
  { nombre: "Taladro Rotopercutor BOSCH SDS GBH-2", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Taladro TOTAL Plus SDS", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Trompito Mesclaor TOTAL", categoria: "Herramientas manuales y pesadas", cantidad: 1, esMaquina: true },
  { nombre: "Alargue", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Amoladora LUSQTOF Mod L820", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Bizcachera C/ accesorios", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Dobladora de caño de 12\"", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Pala de punta mango largo P/ pozo", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Rotomartillo Lusqtof Mod RML 1100", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Sierra Circular BLACK DECKER Mod CS1020", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Alargues", categoria: "Herramientas manuales y pesadas", cantidad: 3 },
  { nombre: "Bidones 10 L", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Bidones 25 L", categoria: "Herramientas manuales y pesadas", cantidad: 3 },
  { nombre: "Desmalezadora ECHO mod 4605", categoria: "Herramientas manuales y pesadas", cantidad: 3 },
  { nombre: "Desmalezadora HUSQVARMA Mod 545 RX", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Desmalezadora LD mod 38.9", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Hacha", categoria: "Herramientas manuales y pesadas", cantidad: 2 },
  { nombre: "Hidrolavadora BOSCH GHP200", categoria: "Herramientas manuales y pesadas", cantidad: 1, esMaquina: true },
  { nombre: "Hidrolavadora BTA CLEANER Mod BT660", categoria: "Herramientas manuales y pesadas", cantidad: 1, esMaquina: true },
  { nombre: "Hidrolavadora KONAN Mod KHI2200", categoria: "Herramientas manuales y pesadas", cantidad: 1, esMaquina: true },
  { nombre: "Hidrolavadora STHIL mod RE110", categoria: "Herramientas manuales y pesadas", cantidad: 1, esMaquina: true },
  { nombre: "Horquillas", categoria: "Herramientas manuales y pesadas", cantidad: 4 },
  { nombre: "Machetes", categoria: "Herramientas manuales y pesadas", cantidad: 2 },
  { nombre: "Maletines Herramientas de mano TOTAL", categoria: "Herramientas manuales y pesadas", cantidad: 2 },
  { nombre: "Manguera 25 Mtros", categoria: "Herramientas manuales y pesadas", cantidad: 2 },
  { nombre: "MotoSierra HUSQVARMA Mod 361", categoria: "Herramientas manuales y pesadas", cantidad: 2 },
  { nombre: "Pala de punta", categoria: "Herramientas manuales y pesadas", cantidad: 3 },
  { nombre: "Rastrillos", categoria: "Herramientas manuales y pesadas", cantidad: 4 },
  { nombre: "Sopladora ECHO mod PB252", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Porta Tubo C/ tubo led", categoria: "Seguridad personal", cantidad: 2 },
  { nombre: "Rotomartillo Lusqtof Mod RML 850", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Balde Limpieza", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Bidon 20L vacio", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Ventosa Triple", categoria: "Herramientas manuales y pesadas", cantidad: 4 },
  { nombre: "Ascensor Morta Cargas", categoria: "Herramientas manuales y pesadas", cantidad: 3, esMaquina: true },
  { nombre: "Motor Monta Cargas / Malacate", categoria: "Herramientas manuales y pesadas", cantidad: 2, esMaquina: true },
  { nombre: "Cajon Herramientas Madera", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Cuerpo Laterale andamios", categoria: "Herramientas manuales y pesadas", cantidad: 42 },
  { nombre: "Barral Andamio Corto", categoria: "Herramientas manuales y pesadas", cantidad: 24 },
  { nombre: "Barral Andamio Largo", categoria: "Herramientas manuales y pesadas", cantidad: 16 },
  { nombre: "Bolsones Tela P/arena", categoria: "Herramientas manuales y pesadas", cantidad: 15 },
  { nombre: "Lateral Andamio", categoria: "Herramientas manuales y pesadas", cantidad: 3 },
  { nombre: "Puntales Metalicos Cortos 1 M", categoria: "Herramientas manuales y pesadas", cantidad: 4 },
  { nombre: "Puntales Metalicos Telescopicos", categoria: "Herramientas manuales y pesadas", cantidad: 539 },
  { nombre: "Cajón madera para Herramientas", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Grupo Generador a gasolina DAEWOO Mod GD8500", categoria: "Herramientas manuales y pesadas", cantidad: 1, esMaquina: true },
  { nombre: "Barandas Metalicas T/ balcon", categoria: "Herramientas manuales y pesadas", cantidad: 20 },
  { nombre: "Base Mesa Caño cuadrado", categoria: "Herramientas manuales y pesadas", cantidad: 2 },
  { nombre: "Barra Roscada de Anclaje", categoria: "Herramientas manuales y pesadas", cantidad: 70 },
  { nombre: "Cebezal de Anclaje", categoria: "Herramientas manuales y pesadas", cantidad: 104 },
  { nombre: "Sogas Largas", categoria: "Herramientas manuales y pesadas", cantidad: 2 },
  { nombre: "Caballete Metalico", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Cabezal P/ Ginche (Malacate Manual)", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Guantes Trabajo gris", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Escalera Madera 10 escalos", categoria: "Obra y construcción", cantidad: 1 },
  { nombre: "Perno Roscado", categoria: "Obra y construcción", cantidad: 57 },
  { nombre: "Pasarela Andamio", categoria: "Obra y construcción", cantidad: 1 },
  { nombre: "Amoladora Bosch chica", categoria: "Herramientas manuales y pesadas", cantidad: 2 },
  { nombre: "Atornilladora Inalambrica", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Amoladora Inalambrica", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Escalera 5 escalones", categoria: "Herramientas manuales y pesadas", cantidad: 3 },
  { nombre: "Extensor", categoria: "Herramientas manuales y pesadas", cantidad: 2 },
  { nombre: "Cuchara Albañil", categoria: "Herramientas manuales y pesadas", cantidad: 2 },
  { nombre: "Remachadora", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Pistola P/ sellador", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Alargue 10 mts", categoria: "Herramientas manuales y pesadas", cantidad: 2 },
  { nombre: "Taladro TOTAL", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Reglas", categoria: "Herramientas manuales y pesadas", cantidad: 3 },
  { nombre: "Nivel de mano", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "Espatula", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
  { nombre: "LLana", categoria: "Herramientas manuales y pesadas", cantidad: 1 },
];
